dist: trusty
language: python
python: "3.5.1"
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y postgresql-plpython3-9.6
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3 # A workaround of known Travis issue: https://github.com/travis-ci/travis-ci/issues/7048
install:
  - pip install -r requirements.txt
before_script:
- psql template1 -c 'create extension hstore;'
- export APP_SETTINGS=ci
script: 
  - make test
notifications:
  email: false
